### ISSUE TITLE
Can't apply

### ISSUE THREAD

**Issue by ThatOneCalculator** [katacarbix/discord-themes#1]
I've installed GlassCord and EnhancedDiscord, but I keep getting this error
![Screen Shot 2020-04-26 at 6 48 57 PM](https://user-images.githubusercontent.com/44733677/80326763-a9441900-87ee-11ea-8df1-890340969f79.png)

**Comment by katacarbix** [comment]
Please don't use my branch.

It looks like you're just missing `C:` before the path. Anything beyond that and you'll need to open an issue [here](https://github.com/AryToNeX/Glasscord/issues) instead.
